version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/lazyorg/
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE*
      - README*
checksum:
  name_template: "checksums.txt"

aurs:
  - name: lazyorg-bin
    homepage: "https://github.com/HubertBel/lazyorg"
    description: "A simple terminal-based calendar and note-taking application."
    license: "MIT"
    maintainers:
      - "Hubert Belanger <hubertolino@icloud.com>"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/lazyorg-bin.git"
    provides:
      - lazyorg
    conflicts:
      - lazyorg
    depends:
      - glibc
      - sqlite
    package: |-
      # Install binary
      install -Dm755 "./lazyorg" "${pkgdir}/usr/bin/lazyorg"

      # Install documentation if present
      if [ -f "./LICENSE" ]; then
        install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/lazyorg/LICENSE"
      fi
      if [ -f "./README.md" ]; then
        install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/lazyorg/README.md"
      fi
    commit_author:
      name: HubertBel
      email: hubertolino@icloud.com
    commit_msg_template: "Update to version {{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
